spring:
  config:
    activate:
      on-profile: prod
  # configuration de la datasource
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  # Configuration de l'adresse email envoyant les messages.
  # Diffère selon les serveurs utilisés. Configuration actuelle pour Gmail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # lance un script sql au lancement de l'application (après DDL) => initialise les données
  sql:
    init:
      data-locations: classpath:import.sql


# permet de débugguer le script sql de lancement
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init: DEBUG

# configuration du chemin de base pour swagger
springdoc:
  swagger-ui:
    path: /swagger

# prop custom pour l'implementation de JWT
app:
  security:
    jwt:
      access-expires-at: 900_000 # 15 min
      refresh-expires-at: 2_592_000_000 # 30 j
      prefix: "Bearer "
      auth-header: "authorization"
      access-secret: ${JWT_SECRET}
      refresh-secret: ${JWT_REFRESH_SECRET}